### ISSUE TITLE
REST API for collecting spans

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger#123]
REST API will be necessary for collecting span from a web browser.

see https://github.com/uber/jaeger-client-node/issues/109

**Comment by badiib** [comment]
doing this now for thrift format with endpoint:

/api/traces?format=Jaeger.thrift as POST

**Comment by badiib** [comment]
See https://github.com/uber/jaeger/pull/156

**Comment by yurishkuro** [comment]
I don't think this is fully solved. For Browser use case we need JSON endpoint. The current binary thrift endpoint is something we need for blackbox monitoring

**Comment by badiib** [comment]
Sounds good, doing this next:

/api/traces?format=Jaeger.json as POST

**Comment by black-adder** [comment]
curious, why are we doing the "Jaeger" prefix for the format? Are we planning on supporting non-jaeger formats in the long distant future?

**Comment by badiib** [comment]
@black-adder i'd prefer to keep that open as a possibility, yes.

**Comment by badiib** [comment]
assigning to vprithvi as well, as he is doing some work on http span submissions.

**Comment by pavolloffay** [comment]
Done, implemented HTTP endpoint for collecting data in jaeger.thrift format and now we have also zipkin `v1/spans` endpoint.
