### ISSUE TITLE
jaeger-agent zipkin compatibility

### ISSUE THREAD

**Issue by vprithvi** [uber/jaeger#129]
The jaeger-agent exposes the Zipkin thrift service only on a UDP port. Because thrift doesn't support a UDP transport out of a box it makes using Jaeger for Zipkin instrumented services difficult. It also makes migrating from Zipkin to Jaeger a nonstarter. 

We should explore adding a HTTP or TCP thrift Zipkin receiver to `jaeger-agent` for compatibility and have tests with existing Zipkin instrumentation. Alternatively, we can refactor Zipkin conversions to a separate agent to reduce complexity in `jaeger-agent`

**Comment by yurishkuro** [comment]
This was done in #180

**Comment by Lupus** [comment]
#180 introduces support for Zipkin HTTP only to collector, but agent is still not capable of Zipkin http endpoint as it seems?

**Comment by jpkrohling** [comment]
No, the agent supports only UDP packets. The payload of those packets might contain Jaeger Thrift (binary/compact) or Zipkin data.
