### ISSUE TITLE
seems no way to specify multiple collectors when starting agent?

### ISSUE THREAD

**Issue by yuekui2** [uber/jaeger#130]
Hi,

Trying to figure out if we could use Jaeger in our product tracing collecting. So far getting working by setting a single collector via -collector.host-port. It seems the way to setup multiple collectors is by some auto discovery mechanism. But I have no idea how this works? Please help.

Thanks.
-Kui

**Comment by yurishkuro** [comment]
@yuekui2 do you use any discovery mechanism in your system already?

**Comment by yurishkuro** [comment]
if not, how do your microservices find each other?

**Comment by yuekui2** [comment]
Right now, our system is only partially using micro services. We have grpc auto discovery, not having auto discovery for other kind of services yet.

**Comment by yuekui2** [comment]
Guess a possible solution is to implement a customized dispatcher. It starts with a fix set, pinging to determine the healthy and notify accordingly.

**Comment by yurishkuro** [comment]
We're using go-kit that has support for a number of discovery systems (consul, etcd, and others). I planned to build direct support for go-kit's `sd` package, but we needed a push model which is still in the works in the kit (https://github.com/go-kit/kit/pull/492). It is possible to hack it though.

Which discovery are you using for grpc?

**Comment by yuekui2** [comment]
we are using etcd, with the grpc recommended external load balancing.

**Comment by valichek** [comment]
@yuekui2 maybe linkerd could be a good option for discovery and load-balancing

**Comment by yurishkuro** [comment]
For static pool of collectors, the addresses can be passed as a comma-separated list to the agent.

Support for other discovery systems is tracked in #213
