### ISSUE TITLE
Query startup should fail when -query.static-files has no trailing slash

### ISSUE THREAD

**Issue by mabn** [uber/jaeger#144]
It turns out that `-query.static-files` requires trailing slash. Without it instead of index.html a HTTP 404 is returned and it's not clear why. It would be good to fail at startup if it's missing.

**Comment by yurishkuro** [comment]
Or perhaps we could add a slash if it's missing instead of failing.

Where I would like it to fail is if the directory doesn't exist, e.g. by trying to open index.html

**Comment by mabn** [comment]
That would work too :)
