### ISSUE TITLE
Improve Cassandra deployment for Kubernetes / OpenShift

### ISSUE THREAD

**Issue by jpkrohling** [uber/jaeger#175]
During the initial Docker/Kubernetes/OpenShift , we took some shortcuts regarding Cassandra and they need to be sorted out.

Points to solve:

- [x] Use a more appropriate Cassandra Docker image
- [x] Wrap the Docker entry point to run a `nodetool drain` on shutdown, as suggested by @jsanda
- [x] Figure out the best approach regarding the replication strategy and datacenter configuration

**Comment by pavolloffay** [comment]
fixed issue for replication strategy https://github.com/jaegertracing/jaeger-kubernetes/issues/15

**Comment by pavolloffay** [comment]
`nodetool drain`  in hawkular-metrics

https://github.com/openshift/origin-metrics/blob/master/cassandra/cassandra-prestop.sh
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/templates/hawkular_cassandra_rc.j2#L114-L123

**Comment by pavolloffay** [comment]
@jpkrohling I think this can be closed

`nodetool drain` https://github.com/jaegertracing/jaeger-kubernetes/pull/21 and https://github.com/jaegertracing/jaeger-openshift/pull/27 

Configuration for replication factor is already in master.
