### ISSUE TITLE
Using HTTP Thrift Endpoint from Spring.Cloud.Sleuth

### ISSUE THREAD

**Issue by LarsMilland** [uber/jaeger#217]
Hi

I am trying to use the HTTP Endpoint Collector to collect some spans in Zipkin Thrift format from a Spring-Boot Spring.Cloud.Sleuth instrumented application.

My client application expects the HTTP endpoint to have /api/v1/spans added to its baseURL - which I understand is the ordinary location of Zipkin Thrift endpoints.

If I understand the HTTP Collector correctly it will expose its endpoint to collect Zipkin traces on /api/traces?format=zipkin.thrift - is that somehow easy to move to /api/v1/spans - as an alias perhaps?

Best regards
Lars Milland

**Comment by black-adder** [comment]
If all zipkin clients expect /api/v1/spans as the HTTP endpoint for zipkin.thrift, I think it makes sense for us to alias our endpoints as such to ease migration for zipkin users. The change shouldn't be too hard on our end.

**Comment by yurishkuro** [comment]
Many Zipkin clients can be configured with the exact URL to submit the spans to. Couldn't you configure Sleuth to do the same? 

The HTTP endpoint on Jaeger collector is _Jaeger's API_, not Zipkin's, so accepting the exact Zipkin URI is not great. At minimum we can open another (optional) port that exactly mirrors Zipkin API, but I would like to see a strong need for it first.

**Comment by LarsMilland** [comment]
We found a working solution for us with the ZipkinSender class.

```java
  @Bean
  public io.opentracing.Tracer zipkinTracer() {
    ZipkinSender sender = ZipkinSender
        .create(nets.eu.URLConnectionSender.builder()
            .endpoint(
                "https://jaeger-http-collector.mydomain.xxx/api/traces?format=zipkin.thrift")
            .compressionEnabled(false).build());
    Metrics metrics = new Metrics(new StatsFactoryImpl(new NullStatsReporter()));
    Reporter reporter = new RemoteReporter(sender, 1000, 100, metrics);
    Sampler sampler = new ProbabilisticSampler(1);
    return new Tracer.Builder("DemoService", reporter, sampler).build();
  }  
```

**Comment by pavolloffay** [comment]
@LarsMilland hi

> We found a working solution for us with the ZipkinSender class.

your code snippet provides OpenTracing tracer bean. Is it consumed by `spring-cloud-sleuth`? To my knowledge sleuth does not work with OpenTracing tracer.

**Comment by LarsMilland** [comment]
@pavolloffay Sorry for being accurate here. We went with a solution with OpenTracing beans as you explain, and not with the Spring Cloud Sleuth, so not used in Spring Cloud Sleuth.

**Comment by pavolloffay** [comment]
NP, then I guess you are using https://github.com/opentracing-contrib/java-spring-web. 

If you would like to have OpenTracing support in sleuth you can express your interest here https://github.com/spring-cloud/spring-cloud-sleuth/issues/599

**Comment by pavolloffay** [comment]
To add more details:

sleuth-zipkin reports spans in JSON format and there is no way to set a query param (e.g. jaeger needs `?format=zipkin.thrift`). 

A possible solution is to open a PR to sleuth repo with jaeger integration.

**Comment by yurishkuro** [comment]
another alternative is to sniff the format from the payload automatically

**Comment by pavolloffay** [comment]
`Content-Type` header should tell us the format. If we want to support zipkin JSON we would have to implement it (thrift JSON protocol does not work here).

**Comment by pavolloffay** [comment]
I have also created this: https://github.com/spring-cloud/spring-cloud-sleuth/issues/628

**Comment by adriancole** [comment]
I agree that it would be better to not use a query parameter to do what Content-Type is used for. Not only will this save embarrassment from api critics, but it will also not require changing all of the various libraries you may want to work seamlessly with your portability thing.
