### ISSUE TITLE
Securing UI of Jaeger

### ISSUE THREAD

**Issue by LarsMilland** [uber/jaeger#218]
Hi

Is it be any means present in the codebase of Jaeger possible to add some security to the UI - such that logins are required, by LDAP, Oauth or similar. Possibly restricting access to different services/subsets of data captured to groups or otherwise granted credentials?

Best regards
Lars Milland

**Comment by black-adder** [comment]
May I ask what the use case for this is? At Uber, every developer inside our VPN can access the UI since it's a developer tool. Are you possibly saving PI in your traces which only a subset of developers are able to view?

We haven't considered these issues atm but would be interested to hear your use case.

**Comment by jpkrohling** [comment]
I would also be interested in the use case. This is a topic that I have on my radar, but I keep thinking that modern deployments are better suited by having a security sidecar/reverse proxy. Keycloak, for instance, does provide a [Security Proxy](https://keycloak.gitbooks.io/documentation/server_installation/topics/proxy.html), and security is one of the listed features of Istio, so, I don't really see an advantage of having the authentication/authorization happening at the Jaeger side.

**Comment by vprithvi** [comment]
Agree with @jpkrohling on this one. Uber also uses [One Login](https://www.onelogin.com/) to secure the UI for access from the Internet.

**Comment by xionglun** [comment]
@black-adder @jpkrohling Here I can give an use case.
Uber is a big enough company now, so you guys can have a good develop environment. Use many tools to keep security. And you may have your own datacenter.
But for many *small* teams,  they have to use public clouds like AWS, Azure. From their computer to dashboard server is not safe, and yes, they can use VPN or something else, but maybe they don't have enough people or enough knowledge or enough motivation to do it. So an account system or LDAP support may be the best solution.

@vprithvi Small teams may even don't know what **One Login** is.

That's all my opinions, Thx.

**Comment by jpkrohling** [comment]
Every minute we spend on building our own auth/z solution for Jaeger is a minute that we could have been working on some improvement to the core solution. I personally believe the auth/z space is full with solutions that will solve this problem in a better and safer way.

Using your example for AWS: you could use a Keycloak Proxy between the public internet and a VPC, where Jaeger would be available. This way, you'd get a really good auth/z solution "for free" (LDAP, 2-Factor auth, Social accounts, brute force attack detection, Kerberos, SSSD, ...), and Jaeger won't have to worry about even the most basic scenarios a auth/z requires nowadays.

**Comment by LarsMilland** [comment]
Having looked at comments and discussion here a side-car option is chosen for my deployment - see more details here on issue #219.

**Comment by jpkrohling** [comment]
JIRA: https://issues.jboss.org/browse/HWKAPM-909

**Comment by yurishkuro** [comment]
can this issue be closed?

**Comment by jpkrohling** [comment]
Yes, this one can be closed.

**Comment by srflaxu40** [comment]
Does Jaeger use react? could we implement something like google or github auth just embedding the react component?

https://github.com/checkr/react-github-login

https://www.npmjs.com/package/react-google-login

**Comment by jpkrohling** [comment]
Yes, it does use React. You can open an issue on the https://github.com/jaegertracing/jaeger-ui repo about this.
