### ISSUE TITLE
Allow Istio to report Zipkin span data to Jaeger

### ISSUE THREAD

**Issue by kevinearls** [uber/jaeger#225]
I've just finished experimenting with Istio on Openshift (based on this blog post:  https://blog.openshift.com/running-istio-service-mesh-openshift/) and tried unsuccessfully to get it to report spans to Jaeger rather than Zipkin.  In order to use Jaeger with Istio, the following 2 items are required:

1.  Determine how to get istioctl kube-inject to set the envoy "collector_endpoint" when deploying an app, and point collector_endpoint at the Jaeger collector.  (This is possible to do directly in Envoy, but I don't know if istio allows it.)
2.  Update the Jaeger collector to accept JSON spans, as this is what Envoy creates.

**Comment by yurishkuro** [comment]
What is the JSON format?

**Comment by kevinearls** [comment]
I'm not exactly sure, I was just assuming whatever Zipkin accepts.  @pavolloffay  do you know, or do you know where I could find this?

**Comment by pavolloffay** [comment]
I guess it is Zipkin JSON format 
collector: https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/ZipkinHttpCollector.java#L64
codec: https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin/internal/JsonCodec.java#L61

**Comment by adriancole** [comment]
Theres an openapi doc in the zipkin-api repo which describes json with one
glitch about the format of binary annotation
https://github.com/openzipkin/zipkin-api/issues/27

Might be that openapi v3 tooling has progressed to the point we can resolve
above.

**Comment by pavolloffay** [comment]
Am working on JSON encoding. In the future we might need C++ OT impl see https://github.com/lyft/envoy/issues/1196.

**Comment by yurishkuro** [comment]
@pavolloffay can this issue be closed now?

**Comment by pavolloffay** [comment]
yes please.
