### ISSUE TITLE
Facing problem while running Hotrod example

### ISSUE THREAD

**Issue by PritomAhmed** [uber/jaeger#232]
Cloned the jaeger repo using go get github.com/uber/jaeger

make install_examples -- worked
cd examples/hotrod -- worked
go run ./main.go all -- failed

Message:

pkg/log/factory.go:24:2: cannot find package "context" in any of:
	/home/pahmed/src/github.com/uber/jaeger/examples/hotrod/vendor/context (vendor tree)
	/home/pahmed/src/github.com/uber/jaeger/vendor/context
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/pahmed/src/context (from $GOPATH)

Not familiar with Go so could be missing something totally obvious ... but thought i would log this as an issue as other noobs like me will likely hit this too.

**Comment by yurishkuro** [comment]
this might be the reason: `/usr/lib/go-1.6`. We only build with 1.7 and up.

**Comment by PritomAhmed** [comment]
Thanks. It worked.
