### ISSUE TITLE
Use spf13/cobra for command line arguments

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger#233]
https://github.com/spf13/cobra is a very nice tool to parse command line arguments. Is there an interest to use it instead of flags?

(I'm new to go, I would like to start with something simple :face_with_head_bandage: )

**Comment by yurishkuro** [comment]
We already use it in the HotROD demo! However, it's mostly useful there because hotrod is a single binary that runs (potentially) multiple services. Since all jaeger components are individual binaries, the standard Go `flag` package works well enough. Which features from cobra do you think will be useful?

**Comment by jpkrohling** [comment]
The ability to have flags on the command line is good, but overriding it via a configuration file / env var is great. In Kubernetes/OpenShift, the configuration file can be a ConfigMap, making it easier to do changes without having to change the DC/RC's command.

**Comment by pavolloffay** [comment]
@yurishkuro should I proceed with it? Will it be accepted?

**Comment by yurishkuro** [comment]
Yes, reading ENV automatically sounds good. Maybe worth doing a small prototype on one of the backend components to see what it looks like with cobra

**Comment by mh-park** [comment]
@yurishkuro @pavolloffay should this be closed? I believe #307 resolved this

**Comment by pavolloffay** [comment]
yes this should be closed

**Comment by yurishkuro** [comment]
I have one issue with the way storage flags are defined, they are still using the struct values as defaults, we moved away from that style in the recent commits.

**Comment by pavolloffay** [comment]
Do you mean https://github.com/uber/jaeger/blob/master/cmd/flags/es/options.go#L64-L86 and https://github.com/uber/jaeger/blob/master/cmd/flags/cassandra/options.go#L66-L86?

**Comment by pavolloffay** [comment]
We could:
1. change `func NewOptions(primaryNamespace string, otherNamespaces ...string) *Options ` to just set namespaces and default props would be defined in `AddFlags`
2. change `AddFlags` and `InitFromViper` to accept list of namespaces and remove `NewOptions`)

**Comment by pavolloffay** [comment]
There is one problem, `Options.Get(namespace)` calls `Configuration.ApplyDefault(other)` (clled after `InitFromViper`) therefore if we use default values in `AddFlags` then these values will be repeated in `ApplyDefaults`.

* Options.Get`: https://github.com/uber/jaeger/blob/43ef964c095bb3c4f08a620f0b5171342be0435a/cmd/flags/es/options.go#L158
* `Configuration.ApplyDefault` https://github.com/uber/jaeger/blob/master/pkg/cassandra/config/config.go#L60

**Comment by yurishkuro** [comment]
@pavolloffay since you did most of the Viper work, do you think it's critical to refactor the storage options? If the existing design doesn't cause problems, we can just move on (minor tech debt/inconsistency).

**Comment by pavolloffay** [comment]
I think it can stay how it is right now. Although I'm still new to golang so hard to say which is the best.

Maybe something will change in the future and it will make it more straight forward to refactor. I can submit a PR with TODO notes.

**Comment by pavolloffay** [comment]
I have created https://github.com/uber/jaeger/pull/329 to add TODO
