### ISSUE TITLE
Unable to start collector with PasswordAuthenticator

### ISSUE THREAD

**Issue by mnaga** [uber/jaeger#255]
Is there an option to pass username/password for cassandra while starting collector?

I dont not see any option to do that

  -cassandra.connections-per-host int
        The number of Cassandra connections from a single backend instance (default 2)
  -cassandra.keyspace string
        The Cassandra keyspace for Jaeger data (default "jaeger_v1_local")
  -cassandra.max-retry-attempts int
        The number of attempts when reading from Cassandra (default 3)
  -cassandra.port int
        The port for cassandra
  -cassandra.proto-version int
        The Cassandra protocol version (default 4)
  -cassandra.servers string
        The comma-separated list of Cassandra servers (default "127.0.0.1")
  -cassandra.socket-keep-alive duration
        Cassandra's keepalive period to use, enabled if > 0
  -cassandra.timeout duration
        Timeout used for queries

**Comment by yurishkuro** [comment]
There is no such option at the moment, but it's not difficult to add. Are you interested in submitting a PR? We have a [Configuration](https://github.com/uber/jaeger/blob/master/pkg/cassandra/config/config.go#L34) struct for Cassandra, I would add an Authenticator field to it, e.g.

```go
type Configuration struct {
    ....
    Authenticator Authenticator `yaml:"authenticator"`
}

type Authenticator struct {
    Basic BasicAuthenticator  `yaml:"basic"`
    // leave the door open to add more auth types in the future, like SSL Cert
}

type BasicAuthenticator struct {
    Username string  `yaml:"username"`
    Password string  `yaml:"password"`
}
```

At the moment we only support passing parameters via command line options, and I think passing password in that way is not the best design. May want to wait for #235 to be resolved, which will allow passing params as env vars, better suited for secrets.

**Comment by mnaga** [comment]
Sure can. I can start by creating a PR by adding auth props to Configuration Struct for cassandra and create new session using it.

Currently, cassandra command line options are bound here https://github.com/uber/jaeger/blob/master/cmd/flags/cassandra/options.go#L101, once #235 is resolved we can have another PR to deal with auth params. Or should this just wait until 235? Thoughts?

**Comment by yurishkuro** [comment]
#235 might take some time, currently part of it was split into agent-only changes and there are some issues with it. Let's definitely do a config struct change, and then it's probably ok to add cmd line props in the current way, then #235 will account for them.

**Comment by kop** [comment]
Can this be released please?
Our company is looking to start using Jaeger, but we can't start without authentication.

**Comment by yurishkuro** [comment]
yes, we'll publish a new release this week

**Comment by yurishkuro** [comment]
@mnaga @kop this has been released in https://github.com/uber/jaeger/releases/tag/v0.6.0
