### ISSUE TITLE
Code for parsing the traces found through T-channel in Jaeger server

### ISSUE THREAD

**Issue by PritomAhmed** [uber/jaeger#258]
Hi,

Can someone help me by pointing out the package where the parsing of the traces found through tchannel is done in Jaeger server ?
Basically I am looking for the source files where the traces are received and parsed in the jaeger server.

Thanks in advance.

**Comment by black-adder** [comment]
https://github.com/uber/jaeger/blob/master/cmd/collector/app/span_handler.go handles traces in the collector and https://github.com/uber/jaeger/blob/master/cmd/collector/main.go#L75 is where the tchannel endpoints are setup

**Comment by PritomAhmed** [comment]
Thanks @black-adder

**Comment by PritomAhmed** [comment]
And where these traces are put in T-channel in the hotrod example ?
I am looking for the code where the T-channel is configured and the code where the traces are sent through T-channel.

**Comment by yurishkuro** [comment]
https://github.com/uber/jaeger/blob/master/cmd/agent/app/reporter/tchannel/reporter.go
