### ISSUE TITLE
Document about Docker is rare

### ISSUE THREAD

**Issue by liubin** [uber/jaeger#259]
I want to run jaeger in Docker, but the Docker image at hub.docker.com has no document, I don't know how to use the `-p` and the `-v` when I run the component.

So I hope these document to be added:

- How to use `docker run`
- The Dockerfile that build the Docker image that at the Docker Hub.

Thanks.

**Comment by omeid** [comment]
There is [jaeger-kubernetes](https://github.com/jaegertracing/jaeger-kubernetes) which is a decent reference to get started.

**Comment by liubin** [comment]
Thanks, you are great.
