### ISSUE TITLE
Can not use 'docker exec' in the docker while it is running

### ISSUE THREAD

**Issue by PritomAhmed** [uber/jaeger#264]
Hi,

I build a local version of jaeger by running the following commands.

1)	./travis/build-all-in-one-image.sh
2)	docker build –f cmd/standalone/Dockerfile –t <image_name> .
3)	docker run -d -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp   -p5778:5778 -p16686:16686 -p14268:14268 <image_name>

Everything works fine unto this point.

I want to see the logs in the jaeger server so I want to use the `docker exec` command to browse the container. I use the following command
`docker exec -it <containerid>  bash`

But I see the following error.

> rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "exec: \"bash\": executable file not found in $PATH"

Thanks in advance.

**Comment by yurishkuro** [comment]
because the base image has no tooling:
```
$ head -2 cmd/standalone/Dockerfile
FROM scratch
```

you can swap it for alpine when building your image.

**Comment by PritomAhmed** [comment]
Thanks @yurishkuro . It worked.
