### ISSUE TITLE
Where can we find the logs in jaeger server ?

### ISSUE THREAD

**Issue by PritomAhmed** [uber/jaeger#265]
Hi,

I am trying to see the logs in jaeger. For instance, I want to use `zap.Logger` to log inside jaeger/cmd/agent/app/reporter/tchannel/reporter.go reporter.go

How can I see these logs ? 
I am able to browse inside the running docker by using the technique mentioned in issue#[264](https://github.com/uber/jaeger/issues/264)

**Comment by yurishkuro** [comment]
Jaeger binaries write to stdout, did you try `docker logs` ?

**Comment by PritomAhmed** [comment]
Thanks @yurishkuro , Using `docker log` helps. 

I am running the Hotrod example, it does not matter how many traces I generate using the Hotrod example, most of the paths in then code base in uncovered. The only files that executes are  cmd/standalone/main.go
cmd/agent/app/reporter/tchannel/builder.go
and peerlistmgr/peer_list_mgr.go

If I want to see the traces that are generated from the Hotrod example, before and after they are passed on through tchannel, what would be the approach ?

Thanks in advance.

**Comment by yurishkuro** [comment]
Sorry, I didn't follow. What are you trying to achieve?

**Comment by PritomAhmed** [comment]
I am trying to store the traces that are generated from the Hotrod example.

**Comment by yurishkuro** [comment]
If you run HotRod as explained in the blog, it will store the traces in the memstore. You can retrieve them in JSON format from the backend

**Comment by PritomAhmed** [comment]
By memstore do you mean the one from tough-cookie ?
Are they stored in the machine I am running Hotrod or in the docker ?

Thanks for you patience.

**Comment by yurishkuro** [comment]
when you run all-in-one Jaeger backend, e.g.

```
go run ./cmd/standalone/main.go --span-storage.type=memory
```

(there's also a docker image), the spans are stored in memory of that process. You can retrieve them in JSON format via api endpoint (UI has JSON view button too).
