### ISSUE TITLE
Multi-trace search fails if a single trace ID doesn't exist

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger#310]
From a user experience point of view, it should show whatever traces it can find. This comes up often when looking at the quality metrics page and trying to see example traces; a single trace that doesn't exist (due to TTLing) can ruin the whole query.

**Comment by black-adder** [comment]
does there need to be UI work for this? @tiffon

**Comment by yurishkuro** [comment]
Yes we do. Current version of the UI does not parse the errors portion of the response, it only seems to react to the status code.

**Comment by yurishkuro** [comment]
let's open an issue in the ui project for that, link here and close this issue.
