### ISSUE TITLE
Cannot find service name in Zipkin span

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger#337]
When testing #334 I discovered that `brave` (or maybe any zipkin instrumentation)  can send span with just one binary annotation 
```
 {  
      "traceId":"549d6e48d3a5bfcbe4a4fbc1284ff98b",
      "id":"b5e1ead09289b182",
      "name":"",
      "parentId":"e4a4fbc1284ff98b",
      "binaryAnnotations":[  
         {  
            "key":"http.status_code",
            "value":"200",
            "endpoint":{  
               "serviceName":"spring-boot",
               "ipv4":"10.43.17.27"
            }
         }
      ]
   }
```
trace: https://paste.fedoraproject.org/paste/4iUxY0cOkfGpz5jQj-K-lA

It results in `Cannot find service name in Zipkin span [traceID=e4a4fbc1284ff98b, spanID=b5e1ead09289b182]` https://github.com/uber/jaeger/blob/79fba1278743840dff6b84aa059ec58f7ec21a0a/model/converter/thrift/zipkin/to_domain.go#L161-L182

![screenshot of jaeger ui](https://user-images.githubusercontent.com/5618424/29317293-847b81c0-81cb-11e7-8580-2d27f9f248ba.jpg)

Reproducer:
https://github.com/pavolloffay/opentracing-java-examples/tree/jaeger-unknown-service-error-and-ui-issues
run spring-boot and `curl localhost:8080/chaining`, Note that it's not deterministic.

**Comment by yurishkuro** [comment]
yeah, the code checks for service name AND ipv4 being defined, I think the IP should be optional. Having said that, the above JSON seems to have ipv4, so not sure why it's not working.

**Comment by pavolloffay** [comment]
fixed in https://github.com/uber/jaeger/pull/378
