### ISSUE TITLE
cassandra image can't use cqlsh : socket.gaierror: [Errno -5] No address associated with hostname

### ISSUE THREAD

**Issue by meilihao** [uber/jaeger#379]
I used jaeger/plugin/storage/cassandra/Dockerfile to build cassandra image, and i found once `ENV CQLSH_HOST=cassandra` is set, `cqlsh` can't be used, got err:
```sh
root@f930497bc2cf:/# env
HOSTNAME=f930497bc2cf
TERM=xterm
CASSANDRA_CONFIG=/etc/cassandra
CQLSH_HOST=cassandra
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GPG_KEYS=514A2AD631A57A16DD0047EC749D6EEC0353B12C 	A26E528B271F19B9E5D8E19EA278B781FE4B2BDA
PWD=/
SHLVL=1
HOME=/root
CASSANDRA_VERSION=3.11.0
GOSU_VERSION=1.10
_=/usr/bin/env
root@f930497bc2cf:/# cqlsh
Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 2428, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/usr/bin/cqlsh.py", line 2407, in main
    encoding=options.encoding)
  File "/usr/bin/cqlsh.py", line 479, in __init__
    load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/policies.py", line 417, in __init__
socket.gaierror: [Errno -5] No address associated with hostname
```

**Comment by pavolloffay** [comment]
So after getting this error you cannot run any `cqlsh` command?

**Comment by jpkrohling** [comment]
Note that this image is not a Cassandra image: it's an image that can be used to create the schema required by Jaeger. One example of usage is here: https://github.com/jaegertracing/jaeger-kubernetes/blob/master/production/jaeger-production-template.yml#L123

If that's indeed what you want, you can be override the target host by setting a new value for the environment variable CQLSH_HOST, like this: `docker run -e CQLSH_HOST=my-cassandra-server.domain.tld`.

**Comment by yurishkuro** [comment]
It's not clear to me if this ticket is a real issue or not. @meilihao why do you need to build an image yourself, given that we publish them to DockerHub?

Do we need to add any documentation? If so, I am not sure what exactly.

**Comment by meilihao** [comment]
@jpkrohling thinks. this is my first to use Cassandra,  and understood the meaning of CQLSH_HOST, so this issue is invalid.

Maybe add some about how to use plugin/storage/cassandra/Dockerfile.
