### ISSUE TITLE
How to run jaeger-agent docker image with collector address configured?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [uber/jaeger#387]
When I run `docker run jaegertracing/jaeger-agent`, I want to configure collector host and port, so that collector can collect the traces metrics, so is there a way to configure collector host and port?

**Comment by jpkrohling** [comment]
`docker run jaegertracing/jaeger-agent /go/bin/agent-linux --collector.host-port=jaeger-collector.jaeger-infra.svc:14267`

**Comment by ggaaooppeenngg** [comment]
thx, it works!

**Comment by yurishkuro** [comment]
If this is unclear from documentation let's keep this open and fix the docs

**Comment by jpkrohling** [comment]
Could you please assign this to me?

**Comment by yurishkuro** [comment]
@jpkrohling - go for it (github assign does't work)
