### ISSUE TITLE
How to start Jaeger?

### ISSUE THREAD

**Issue by jeluard** [uber/jaeger#43]
_Sorry for hijacking issues but this looks like the only way to contact the team._

I don't know much about go. Could you share some basic details on how to start jaeger daemon/UI?

Thanks in advance!

**Comment by black-adder** [comment]
Hi, we're still in the process of moving the Jaeger codebase from our internal repo to Github. Once we're ready, we'll have a deployment guide for you.

**Comment by jeluard** [comment]
Great thanks!
