### ISSUE TITLE
Hotrod example doesn't work 

### ISSUE THREAD

**Issue by LoungeFlyZ** [uber/jaeger#73]
- Cloned the jaeger repo
- make install_examples -- worked
- cd examples/hotrod -- worked
- go run ./main.go all -- failed

```/Users/Chris/go/src/github.com/uber/jaeger/examples/hotrod/cmd/customer.go:28:2: code in directory /Users/Chris/go/src/github.com/uber-go/zap expects import "go.uber.org/zap"```

Not familiar with Go so could be missing something totally obvious ... but thought i would log this as an issue as other noobs like me will likely hit this too.

**Comment by yurishkuro** [comment]
On the first look everything seems ok, the Travis build did compile hotrod successfully

https://travis-ci.org/uber/jaeger#L552

**Comment by yurishkuro** [comment]
I tried a few things, all seem to work for me. One strange thing about the error you have is that it refers to `/Users/Chris/go/src/github.com/uber-go/zap` - instead it should be looking for it under the `./vendor` dir.

**Comment by dianvaltodorov** [comment]
@LoungeFlyZ  How did you get the source code?
Was it with `go get github.com/uber/jaeger` or with `git clone https://github.com/uber/jaeger.git`?

If it was with `git clone` it would not work. Instead use the `go get github.com/uber/jaeger` and check if it does?

**Comment by LoungeFlyZ** [comment]
Thanks @dianvaltodorov,  it was with git clone.  I did that because go get didnt work either. Here is what i got:

`can't load package: package github.com/uber/jaeger: no buildable Go source files in /Users/Chris/go/src/github.com/uber/jaeger`

**Comment by yurishkuro** [comment]
@LoungeFlyZ we may need to put a dummy file in the root to make sure `go get` works.  If you're using `git clone`, you need to make sure the target dir follows Go convention, i.e. it should be cloned into `$GOPATH/src/github.com/uber/jaeger`

**Comment by yurishkuro** [comment]
I added `doc.go`, so that `go get` now works.

**Comment by LoungeFlyZ** [comment]
@yurishkuro that seemed to fix the `go get` issue. 

Now when i get to the next step it doesnt want to run:

`
 Chris@Christophers-MacBook-Pro-2  ~/go/src/github.com/uber/jaeger/examples/hotrod   master  go run ./main.go all
pkg/log/factory.go:27:2: cannot find package "go.uber.org/zap" in any of:
	/Users/Chris/go/src/github.com/uber/jaeger/examples/hotrod/vendor/go.uber.org/zap (vendor tree)
	/usr/local/Cellar/go/1.8/libexec/src/go.uber.org/zap (from $GOROOT)
	/Users/Chris/go/src/go.uber.org/zap (from $GOPATH)
pkg/log/factory.go:28:2: cannot find package "go.uber.org/zap/zapcore" in any of:
	/Users/Chris/go/src/github.com/uber/jaeger/examples/hotrod/vendor/go.uber.org/zap/zapcore (vendor tree)
	/usr/local/Cellar/go/1.8/libexec/src/go.uber.org/zap/zapcore (from $GOROOT)
	/Users/Chris/go/src/go.uber.org/zap/zapcore (from $GOPATH)
`

Ideas?

**Comment by yurishkuro** [comment]
I think it was missing the main install, I just pushed a change to the Makefile.

**Comment by yurishkuro** [comment]
Please reopen if you still have the issue.

**Comment by mfilotto** [comment]
Hi,
I get an error too
```
[vagrant@vm-dev-sln jaeger]$ go get github.com/uber/jaeger
package github.com/uber/jaeger: no buildable Go source files in /home/vagrant/go/src/github.com/uber/jaeger

[vagrant@vm-dev-sln jaeger]$ go get github.com/jaegertracing/jaeger
package github.com/jaegertracing/jaeger: no buildable Go source files in /home/vagrant/go/src/github.com/jaegertracing/jaeger
```

**Comment by yurishkuro** [comment]
@mfilotto fixed by https://github.com/jaegertracing/jaeger/commit/c32f9602b8f43595025d8cd42f3a6c1d062a4238

however, that error was not fatal, the code is stil downloaded
