### ISSUE TITLE
Modify the limit behavior in our queries

### ISSUE THREAD

**Issue by badiib** [uber/jaeger#83]
Since reverting away from SASI indices, we need to artificially increase our limit number during queries and then shed off excessive traceIDs after results from cassandra.

**Comment by badiib** [comment]
This may or may not include removing limit for index queries and then shedding off any excessive traceIDs.

**Comment by yurishkuro** [comment]
I am against removing the limit altogether. There's nothing magic about the 10000, it's just the default value of LIMIT in C, why should we rely on that instead of setting our own?

**Comment by badiib** [comment]
@yurishkuro I think we should go with some hardcoded multiplier, at which points we dump traceIds into the UniqueTraceIDs, pairing down the number of IDs we pull from the traces table to limit.

**Comment by yurishkuro** [comment]
seems reasonable. What multiplier does zipkin use?

**Comment by badiib** [comment]
Looks like it's 3: https://github.com/openzipkin/zipkin/search?utf8=%E2%9C%93&q=indexFetchMultiplier&type=

We can tune this, but let's start with 3.

**Comment by apoorv007** [comment]
Shouldn't this limit be different for the cases when querying using both service and operation Vs. when querying using only service - since the chances of collision are also different in the two cases.
